ssl:
  port: 21171
  protocols: 'SSLv3'
  cipher-suites: 'SSL_RSA_WITH_RC4_128_MD5,SSL_RSA_WITH_RC4_128_SHA'
  debug:
    enabled: false
tcp:
  port: 21172
  debug:
    enabled: true
    exclusions: '~png'
udp:
  port: 1
  debug:
    enabled: true

spring:
  datasource:
    url: jdbc:h2:file:./data/heroesDB
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
