server:
  port: 8080

ssl:
  protocols: 'SSLv3'
  cipher-suites: 'SSL_RSA_WITH_RC4_128_MD5,SSL_RSA_WITH_RC4_128_SHA'
  debug:
    enabled: false
tcp:
  port: 21172
  debug:
    enabled: false
    exclusions: '~png'
udp:
  port: 21173
  debug:
    enabled: true

nfs:
  ip: '192.168.1.11' # Requires machine IP
  tcp:
    port: 9900
  udp:
    port: 3658

spring:
  profiles:
    active:
      - pal
  datasource:
    url: jdbc:h2:mem:mohh2db
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
       ddl-auto: none
  h2:
    console:
      enabled: true
      path: /h2
  sql:
    init:
      mode: always
      platform: h2


---
spring:
  config:
    activate:
      on-profile: pal

ssl:
  port: 21171

---
spring:
  config:
    activate:
      on-profile: ntsc

ssl:
  port: 21121
