server:
  port: 8080

ssl:
  protocols: 'SSLv3'
  cipher-suites: 'SSL_RSA_WITH_RC4_128_MD5,SSL_RSA_WITH_RC4_128_SHA'
  debug:
    enabled: false
tcp:
  host: ${HOST_IP:127.0.0.1} # Must be machine IP if hosting for other machines. Must be WSL IP if using docker through WSL (local only).
  debug:
    enabled: false
    exclusions: '~png'
udp:
  host: ${HOST_IP:127.0.0.1} # Must be machine IP if hosting for other machines. Must be WSL IP if using docker through WSL (local only).
  connect-mode.enabled: false # false = listen-mode (default), must replace '41' by '40' at 0x8001BEB4 if set to true
  debug:
    enabled: false

spring:
  profiles:
    active:
      - pal
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
#  jpa:
#    hibernate:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true

ssc2:
  key: 51ba8aee64ddfacae5baefa6bf61e009

---
spring:
  config:
    activate:
      on-profile: pal

ssl:
  port: 21171
tcp:
  port: ${PAL_TCP_PORT:21172}
udp:
  port: ${PAL_UDP_PORT:21173}

---
spring:
  config:
    activate:
      on-profile: ntsc

ssl:
  port: 21121
tcp:
  port: ${NTSC_TCP_PORT:21172}
udp:
  port: ${NTSC_UDP_PORT:21173}
