ssl:
  protocols: 'SSLv3'
  cipher-suites: 'SSL_RSA_WITH_RC4_128_MD5,SSL_RSA_WITH_RC4_128_SHA'
  certificate:
    cipher-algorithm: 'MD5WITHRSA'
  debug:
    enabled: ${SSL_DEBUG_ENABLED:false}
tcp:
  # Must be machine IP if hosting for other machines. Must be WSL IP if using docker through WSL (local only)
  host: ${TCP_HOST_IP:127.0.0.1}
  debug:
    enabled: ${TCP_DEBUG_ENABLED:false}
    exclusions: '~png'
udp:
  # Must be machine IP if hosting for other machines. Must be WSL IP if using docker through WSL (local only)
  # udp.enabled must be set to true if connecting to this server instead of 127.0.0.1 (serverless)
  host: ${UDP_HOST_IP:127.0.0.1}
tos:
  enabled: ${TOS_ENABLED:true} # Stats socket servers on port 80 and 443 to handle TOS HTTP(S) requests
ssc2:
  key: 51ba8aee64ddfacae5baefa6bf61e009
lobby:
  close-expired: ${LOBBY_CLOSE_EXPIRED:true}

spring:
  profiles:
    active:
      - wii-pal
  datasource:
    url: ${DB_URL}
    port: ${DB_PORT:5432}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
#  jpa:
#    hibernate:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true


---
spring:
  config:
    activate:
      on-profile: wii-pal

ssl:
  port: 21171
tcp:
  port: 21172
udp:
  port: 21173

---
spring:
  config:
    activate:
      on-profile: wii-ntsc

ssl:
  port: 21121
tcp:
  port: 21122
udp:
  port: 21123

---
spring:
  config:
    activate:
      on-profile: psp-pal

ssl:
  port: 21181
tcp:
  port: 21182
udp:
  port: 21183

---
spring:
  config:
    activate:
      on-profile: psp-ntsc

ssl:
  port: 21191
tcp:
  port: 21192
udp:
  port: 21193
