server:
  port: 8080

ssl:
  protocols: 'SSLv3'
  cipher-suites: 'SSL_RSA_WITH_RC4_128_MD5,SSL_RSA_WITH_RC4_128_SHA'
  debug:
    enabled: false
tcp:
  port: 21172
  host: 127.0.0.1 # Must be machine IP if hosting for other machines. Must be WSL IP if using docker through WSL (local only).
  debug:
    enabled: true
    exclusions: '~png'
udp:
  port: 21173
  host: 127.0.0.1 # Must be machine IP if hosting for other machines. Must be WSL IP if using docker through WSL (local only).
  connect-mode.enabled: false # false = listen-mode (default), must replace '41' by '40' at 0x8001BEB4 if set to true
  debug:
    enabled: true

spring:
  profiles:
    active:
      - pal
  datasource:
    url: jdbc:h2:mem:mohh2db
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
       ddl-auto: none
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  sql:
    init:
      mode: always
      platform: h2

ssc2:
  key: 51ba8aee64ddfacae5baefa6bf61e009

---
spring:
  config:
    activate:
      on-profile: pal

ssl:
  port: 21171

---
spring:
  config:
    activate:
      on-profile: ntsc

ssl:
  port: 21121
