ALTER TABLE public.GAME_REPORT RENAME COLUMN GREENTHROW TO GRENTHROW;
ALTER TABLE public.GAME_REPORT RENAME COLUMN GRENADEKILL TO GRENKILL;

ALTER TABLE public.PERSONA_STATS RENAME COLUMN GREENTHROW TO GRENTHROW;
ALTER TABLE public.PERSONA_STATS RENAME COLUMN GRENADEKILL TO GRENKILL;
